env: "local" # dex, prod
# storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # время на чтение или время на отправку ответа
  idle_timeout: 60s # время жизни соединения с клиентом